### ISSUE TITLE
Dockerfile is missing

### ISSUE THREAD

**Issue by smclernon** [mattjtodd/winemag-data-jupyter#1]
On a fresh build, if you run a docker-compose up then it will try and build the images.

```
docker-compose up
Creating network "winemag-data-jupyter_default" with the default driver
Building notebook
ERROR: Cannot locate specified Dockerfile: Dockerfile
version: '3.4'
```

This can be fixed by deleting the build directive from the compose file, then it will download the published image.

However, it would be interesting to see how the image has been built!

**Comment by mattjtodd** [comment]
That's a hangover from when I was building the image, now it just uses the vanilla one with the digest.  I accidentally left the build directive in there.  Will resolve shortly....
